services:
  angular-fragment:
    build:
      context: ./angular-fragment
      dockerfile: Dockerfile
    ports:
      - "8083:4000"

  astro-fragment:
    build: 
      context: ./astro-fragment
      dockerfile: Dockerfile
    ports:
      - "8081:4321"
  thymeleaf-fragment:
    build: 
      context: ./thymeleaf-fragment
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
  astro-shell:
    build: 
      context: ./astro-shell
      dockerfile: Dockerfile
    ports:
      - "8080:4321"
